services:
    _defaults:
        public: false
        tags:
            - console.command

    bastsys.cdn_bundle.command.file.check:
        class: BastSys\CdnBundle\Command\FileCheckCommand
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@bastsys.cdn_bundle.repository.file'
            - '@bastsys.cdn_bundle.file_service'


