services:
    _defaults:
        public: false

    bastsys.cdn_bundle.file_service:
        class: BastSys\CdnBundle\Service\UploadedFileService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%cdn.storage.path%'
    bastsys.cdn_bundle.file_link_service:
        class: BastSys\CdnBundle\Service\UploadedFileLinkService
        arguments:
            - '@router.default'
